version: '3.4'
services:
  chat-masterclassroom:
    image: ghcr.io/victordrnd/chat-masterclassroom
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3005:3005"
    depends_on:
      - redis-prof
    labels:
        - traefik.enable=true
        - "traefik.http.routers.dev-chat-api-service-https.rule=Host(`dev-chat-api.master-classroom.com`)"
        - traefik.http.routers.dev-chat-api-service-https.tls=true
        - traefik.http.routers.dev-chat-api-service-https.tls.certresolver=lets-encrypt
        - "traefik.http.routers.dev-chat-api-service-https.entrypoints=websecure"
        - "traefik.http.routers.admin-router-http.service=dev-chat-api-service"
        - "traefik.http.services.dev-chat-api-service.loadbalancer.server.port=3000"

        - "traefik.http.routers.dev-chat-socket-service-https.rule=Host(`socket.master-classroom.com`)"
        - traefik.http.routers.dev-chat-socket-service-https.tls=true
        - traefik.http.routers.dev-chat-socket-service-https.tls.certresolver=lets-encrypt
        - "traefik.http.routers.dev-chat-socket-service-https.entrypoints=websecure"
        - "traefik.http.routers.admin-router-http.service=dev-chat-socket-service"
        - "traefik.http.services.dev-chat-socket-service.loadbalancer.server.port=3005"

        - "traefik.docker.network=web"
    networks:
      - web

  redis-prof:
    image: "redis:alpine"
    restart: unless-stopped
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - web


  # mysql:
  #   image: 'mariadb:10.3'
  #   container_name: mysql
  #   restart: always
  #   environment:
  #      MYSQL_USER: prof
  #      MYSQL_PASSWORD: prof69260
  #      MYSQL_DATABASE: prof
  #      MYSQL_ROOT_PASSWORD: prof69260
  #   ports:
  #       - '127.0.0.1:3306:3306'
  #   volumes:
  #       - ./mysql_prof/:/var/lib/mysql/
  #   networks:
  #     - web


networks:
  web:
    external:
      name: web