urls:
  api: 'https://devnet-api.elrond.com'
  swagger:
    - 'http://192.168.1.186:3000'
  redis: '127.0.0.1'
database:
  host: 'localhost'
  port: 3306
  username: 'victor'
  password: 'root'
  name: 'prof'
s3:
   secretKey: "kBGOJZr2OnhlHtTBnD3GFCOUAJtRMqJj"
   accessKey : "bqXVNJ1xpEON2p0C"
   endpoint: "https://s3.master-classroom.com"
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: false
    port: 4000
  cacheWarmer:
    enabled: false
    port: 5201
  queueWorker:
    enabled: false
    port: 8000
  keepAliveAgent:
    enabled: false
security:
  jwtSecret: 'pIG7fgPNTaI9wENv6Lhd1JeEyejvxOtAzPX8aOCq9GBd8RVlsWsxGZPTZlDrY94q'
  admins:
maps:
  jwt : 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJtYXBzYXBpIiwidGlkIjoiN1A4UFAyOTNaUSIsImFwcGlkIjoiN1A4UFAyOTNaUS5tYXBzLm1hc3Rlci1jbGFzc3Jvb20uY29tIiwiaXRpIjpmYWxzZSwiaXJ0IjpmYWxzZSwiaWF0IjoxNjU3ODk4OTUyLCJleHAiOjE2NTc5MDA3NTJ9.uT7pTchQhZNfV0LjnhmsnJ24sZYAEV8g49luNmHpvSORuFyTIBhFl1j1FIGRJ40o9j0cDSNZipGriCa-lbMG2g'
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
