name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env:
          DEV_ENV : ${{ secrets.SECRET_IP }}
        with:
          push: true
          tags: ghcr.io/victordrnd/chat-masterclassroom:latest
          build-args: |
            DEV_ENV=${{ secrets.DEV_ENV }}
            FCM=${{ secrets.FCM }}