name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - 
        name: Get secret from base64
        uses: actions/checkout@v2
        env:
          DEV_ENV: ${{ secrets.DEV_ENV }}
          WORKSPACE : ${{ github.workspace }}
        run: |
          echo import certificate from secrets and regenerate the file
          echo $DEV_ENV | base64 -d > $WORKSPACE/config/config.yaml
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/victordrnd/chat-masterclassroom:latest